"""`what drives <column> in <file.csv>` and `anomalies in <column> in <file.csv>`: Codex's
ANALYTICS-04 (`analytics/diagnostics.py`, contract in docs/analytics.md) over a CSV of the
user's own. Computed, never generated by a model.

The table is read the way `forecast` reads it - one reader, one number parser, a blank or odd
cell refused with its row - and the answer says only what the core established: an
association is never called a cause, accuracy comes only from rows the fit never saw, and a
value the core could not score is shown as unscored, never as an anomaly or as nothing.
"""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass
from pathlib import Path

from laptop_agent.analytics.diagnostics import anomalies, drivers
from laptop_agent.tools.base import ToolResult
from laptop_agent.tools.files import parse_number
from laptop_agent.tools.forecast import _TRAILING, SeriesError, _column, _date, _numbers, _rows, _shown

DRIVERS_USAGE = "what drives <column> in <file.csv> [using <column>, <column>] [by <date column>]"
ANOMALIES_USAGE = "anomalies in <column> in <file.csv> [by <label column>]"

_FILE = r"(?P<path>\"[^\"]+\.(?:csv|tsv)\"|\S.*?\.(?:csv|tsv))(?P<rest>(?:\s.*)?)"
_DRIVERS = re.compile(r"(?:what\s+drives|drivers\s+of)\s+(?P<column>.+?)\s+(?:in|from)\s+" + _FILE,
                      re.IGNORECASE | re.DOTALL)
_ANOMALIES = re.compile(r"(?:anomalies|outliers|unusual\s+values)\s+(?:in|of)\s+(?P<column>.+?)\s+(?:in|from)\s+"
                        + _FILE, re.IGNORECASE | re.DOTALL)
_DRIVERS_ASK = re.compile(r"\s*(?:what\s+drives|drivers\s+of)\b", re.IGNORECASE)
# A sentence that starts like one of these and names a table is ours whether or not it parses,
# as with `forecast`: unparsed, it would go on to be answered as something else.
_NAMES_TABLE = re.compile(r"\s*(?:what\s+drives|drivers\s+of|anomalies|outliers|unusual\s+values)\b.*\.(?:csv|tsv)\b",
                          re.IGNORECASE | re.DOTALL)
_CLAUSE = re.compile(r"\s+(by|using)\s+", re.IGNORECASE)


@dataclass(frozen=True)
class DriversRequest:
    target: str
    path: str
    features: tuple[str, ...]   # none named: every other column that is all numbers
    order_by: str | None


@dataclass(frozen=True)
class AnomaliesRequest:
    column: str
    path: str
    label_by: str | None


def _clauses(rest: str, allowed: set[str]) -> dict[str, str] | None:
    """The `by` and `using` clauses after the file, in either order; None for anything else."""
    parts = _CLAUSE.split(rest)
    if parts[0].strip():
        return None
    found: dict[str, str] = {}
    for keyword, value in zip(parts[1::2], parts[2::2]):
        keyword = keyword.lower()
        if keyword not in allowed or keyword in found or not value.strip():
            return None
        found[keyword] = value.strip()
    return found


def diagnostics_request(command: str) -> DriversRequest | AnomaliesRequest | None:
    """What `command` asks of a table, or None when it asks neither of these."""
    text = _TRAILING.sub("", command.strip())
    if (match := _DRIVERS.fullmatch(text)) is not None:
        if (clauses := _clauses(match["rest"], {"by", "using"})) is None:
            return None
        named = tuple(name.strip() for name in re.split(r",|\s+and\s+", clauses.get("using", "")) if name.strip())
        return DriversRequest(match["column"].strip(), match["path"].strip('"'), named, clauses.get("by"))
    if (match := _ANOMALIES.fullmatch(text)) is not None:
        if (clauses := _clauses(match["rest"], {"by"})) is None:
            return None
        return AnomaliesRequest(match["column"].strip(), match["path"].strip('"'), clauses.get("by"))
    return None


def diagnostics_command(command: str) -> ToolResult | None:
    """The diagnostic `command` asks for, run; a usage reply when it names a table but cannot be
    followed; None when it is neither, which leaves it to everything else."""
    request = diagnostics_request(command)
    if isinstance(request, DriversRequest):
        return run_drivers(request)
    if isinstance(request, AnomaliesRequest):
        return run_anomalies(request)
    if _NAMES_TABLE.match(command):
        usage = DRIVERS_USAGE if _DRIVERS_ASK.match(command) else ANOMALIES_USAGE
        return ToolResult.failure(f"That names a table, but I could not follow the rest. Use: {usage}")
    return None


def _numeric_columns(header: list[str], body: list[list[str]], exclude: set[int | None]) -> tuple[list[int], list[str]]:
    """Every column whose cells are all numbers, and the names of the rest, so that nothing is
    left out without being said."""
    chosen, skipped = [], []
    for at, name in enumerate(header):
        if at in exclude:
            continue
        cells = [row[at] if at < len(row) else "" for row in body]
        if all(cell.strip() and parse_number(cell) is not None for cell in cells):
            chosen.append(at)
        else:
            skipped.append(name or f"column {at + 1}")
    return chosen, skipped


def _order(header: list[str], body: list[list[str]], at: int) -> list[int]:
    """Row positions sorted by the dates in column `at`; a cell that is not a date is refused."""
    days = []
    for line, row in enumerate(body, start=2):
        cell = row[at] if at < len(row) else ""
        if (day := _date(cell)) is None:
            raise SeriesError(f"Row {line}: '{cell.strip()}' in {header[at]} is not a date I can read "
                              "(try 2025-03-14 or 2025-03).")
        days.append(day)
    return sorted(range(len(body)), key=days.__getitem__)


def run_drivers(request: DriversRequest) -> ToolResult:
    try:
        header, body = _rows(Path(request.path).expanduser())
        target_at = _column(header, request.target, body, numeric=True)
        order_at = _column(header, request.order_by, body, numeric=False) if request.order_by else None
        if request.features:
            feature_at, skipped = [_column(header, name, body, numeric=True) for name in request.features], []
        else:
            feature_at, skipped = _numeric_columns(header, body, {target_at, order_at})
        if target_at in feature_at:
            raise SeriesError(f"{header[target_at]} cannot explain itself; leave it out of `using`.")
        if not feature_at:
            raise SeriesError(f"There is no column of numbers besides {header[target_at]} to compare it with.")
        rows = _order(header, body, order_at) if order_at is not None else list(range(len(body)))
        target = _numbers(header, body, target_at)
        columns = [_numbers(header, body, at) for at in feature_at]
        result = drivers([[column[i] for column in columns] for i in rows], [target[i] for i in rows],
                         feature_names=[header[at] for at in feature_at])
    except ValueError as exc:   # SeriesError, or one of the core's own input limits
        return ToolResult.failure(str(exc))
    target_name, name = header[target_at], Path(request.path).name
    if not result.enough_data:
        # No coefficient is shown at all: the core could not fit and score one.
        return ToolResult.failure(f"I can't say what moves with {target_name} in {name} yet: {result.reason}.",
                                  drivers=asdict(result))
    strongest = sorted(range(len(result.feature_names)), key=lambda j: -abs(result.standardized_coefficients[j]))
    lines = [f"**What moves with {target_name}** (from {name}: fitted on the first {result.train_rows} rows, "
             f"scored on the last {result.test_rows})", ""]
    if order_at is None:
        lines += [f"_Taking the rows of {name} in file order, so the last {result.test_rows} are the held-out ones._", ""]
    lines += ["| Feature | Association | VIF |", "|---|---:|---:|"]
    lines += [f"| {result.feature_names[j]} | {result.standardized_coefficients[j]:+.2f} | {result.vif[j]:.1f} |"
              for j in strongest]
    lines += ["", f"Association: standard deviations of {target_name} per standard deviation of the feature, "
                  "the others held fixed, in the rows it was fitted on."]
    # Scored where nothing was fitted, so this is evidence; the fit itself is not.
    lines.append(f"On the last {result.test_rows} rows, which played no part in the fit, its average miss was "
                 f"{_shown(result.mae)}, against {_shown(result.baseline_mae)} for the training average.")
    if result.out_of_sample_r2 is not None:
        lines.append(f"R² on those rows, against their own average: {result.out_of_sample_r2:.2f}.")
    lines.append("Cautions: " + "; ".join(result.warnings) + ".")
    if skipped:
        lines.append(f"Left out, as not all numbers: {', '.join(skipped)}.")
    return ToolResult.success("\n".join(lines), drivers=asdict(result))


def run_anomalies(request: AnomaliesRequest) -> ToolResult:
    try:
        header, body = _rows(Path(request.path).expanduser())
        value_at = _column(header, request.column, body, numeric=True)
        label_at = _column(header, request.label_by, body, numeric=False) if request.label_by else None
        values = _numbers(header, body, value_at)
        result = anomalies(values)
    except ValueError as exc:   # SeriesError, or one of the core's own input limits
        return ToolResult.failure(str(exc))

    def label(i: int) -> str:
        cell = body[i][label_at].strip() if label_at is not None and label_at < len(body[i]) else ""
        return cell or f"row {i + 2}"

    column, name = header[value_at], Path(request.path).name
    lines = [f"**Unusual {column} values** (from {name}, {len(values)} rows)", ""]
    if result.mad == 0:
        # Not an anomaly and not nothing: a distance with no scale to judge it against.
        lines.append(f"At least half the values are exactly {_shown(result.median)}, so their spread (MAD) is zero "
                     "and no value can be scored.")
        if result.unscored_indices:
            lines += ["", f"These differ from {_shown(result.median)}, by amounts nothing here can call large or small:",
                      "", "| Row | Value |", "|---|---:|"]
            lines += [f"| {label(i)} | {_shown(values[i])} |" for i in result.unscored_indices]
    else:
        lines.append(f"Median {_shown(result.median)}, typical distance from it (MAD) {_shown(result.mad)}. A value is "
                     f"flagged when its modified z-score passes ±{result.threshold:g}.")
        if result.indices:
            ranked = sorted(result.indices, key=lambda i: -abs(result.scores[i]))
            lines += ["", "| Row | Value | Score |", "|---|---:|---:|"]
            lines += [f"| {label(i)} | {_shown(values[i])} | {result.scores[i]:+.1f} |" for i in ranked]
        else:
            lines += ["", "No value is unusual by this measure."]
        if result.unscored_indices:
            lines.append(f"Too far out to score: {', '.join(label(i) for i in result.unscored_indices)}.")
    lines += ["", "_One measure for the whole column: a trend or a season can make ordinary values look unusual._"]
    cautions = [warning for warning in result.warnings if not warning.startswith("MAD is zero")]
    if cautions:
        lines.append("Cautions: " + "; ".join(cautions) + ".")
    return ToolResult.success("\n".join(lines), anomalies=asdict(result))
